
version: '3.0'
services:
  web:
    build:
        .
    ports:
        - "5000:5000"
    depends_on:
        - redis
    volumes:
      - .:/code
    # TODO: build context, ports and redis dependency
    environment:
      # Makes flask to reload code on change
      FLASK_ENV: development
      REDIS_HOST: redis
      REDIS_PORT: 6379
  redis:
    image: redis:6.0-rc4-alpine
    # TODO: missing persistence for redis. You need to persist /data directory.
    volumes:
        - "redis-data:/data"
volumes:
    redis-data:

